### ISSUE TITLE
UI Conflict and with Zygor 

### ISSUE THREAD

**Issue by cwwood0322** [Alastair-Scott/AltReps#9]
I have discovered that I have to disable AltReps so that the character frame isn't messed up and so the in-game Zygor addon works. I use ElvUI as my user interface. After troubleshooting through my many addons, I have discovered it is only AltReps that is affecting both the character frame and the use of the in game Zygor addon. This was not an issue before the pre-patch.

**Comment by Alastair-Scott** [comment]
Hey, thanks for raising this!

For now, you should be able to go into the config for AltReps (either right click the minimap icon, type '/ar config' or go Esc > Interface > Addons > AltReps) and untick the second checkbox ('Show reputation tab button')

It sounds like the Zygor addon is doing something with the Character frames, and my addon is having a conflict with it.

When I get some time, I'll look into what's causing the conflict so that I can fix it.

If you could let me know if the suggestion above fixes the situation for now, I would greatly appreciate it.

Thanks, and have a great adventure through the Shadowlands!

Alastair

**Comment by deetydoc** [comment]
Hello, I have this same issue. I have to disable AltReps in order for Zygor to function at all. I did try unticking the button you referenced but it did not help the problem.  :(

**Comment by Alastair-Scott** [comment]
Hi both, I hope you're doing well?

If you both happen to still be playing, I believe that I have now fixed the issue of the conflict with Zygor.

If I haven't, please let me know and I'll investigate this further!

Many thanks,
Alastair
